### ISSUE TITLE
作者，想请教一下图片拍摄完成后成像的code

### ISSUE THREAD

**Issue by IOCloudFly** [smewise/Camera2#10]
请问一下，如何把横向拍摄或者前置拍摄的图片设置成正方向，问下相关代码

**Comment by smewise** [comment]
int jpegRotation = CameraUtil.getJpgRotation(characteristics, mDeviceRotation);
builder.set(CaptureRequest.JPEG_ORIENTATION, jpegRotation);
正常情况只需要设置JPEG_ORIENTATION就可以了, 但有的手机设置了还是有问题, 这个时候要根据exif信息进行旋转(FileSaver.java中有相关代码),如果根据exif信息旋转了过后还有问题, 我就不太清楚原因了,得拿到具体手机调试一下才知道
