### ISSUE TITLE
大佬，我如果想全屏预览怎么能让预览图形不变形呢，初学者望回复

### ISSUE THREAD

**Issue by NickTet** [smewise/Camera2#11]
大佬，我如果想全屏预览怎么能让预览图形不变形呢，初学者望回复

**Comment by smewise** [comment]
预览分辨率比例和屏幕比例保持一致就可以了, 如果没有屏幕比例比较特殊, 没有对应的预览比例, 那就做不到全屏预览了

**Comment by NickTet** [comment]
嗯 暂时是这样做的 谢谢
