### ISSUE TITLE
大佬，能否给个联系方式

### ISSUE THREAD

**Issue by IOCloudFly** [smewise/Camera2#8]
我想问你一些Camera2的问题

**Comment by smewise** [comment]
> 我想问你一些Camera2的问题

smewise@163.com 邮件交流吧

**Comment by IOCloudFly** [comment]
有些地方没备注，不知道那些类干嘛用的，也不太清楚，那些功能如何实现的，比如设置不同的分辨率啊，视频如何录制的

**Comment by zhaowenliang** [comment]
可以单独写一篇文章写一下项目设计结构吗，看不大懂。。。

**Comment by smewise** [comment]
之前有打算写篇文章介绍下, 但现在工作太忙了, 得等有空再写

**Comment by zhaowenliang** [comment]
谢谢了
